with-expecter: False
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}Mock"
outpkg: "{{.PackageName}}"
filename: "{{.InterfaceName | snakecase}}_mock.go"
all: True
packages:
  github.com/dangquyitt/tech-explorer/mockery/internal/translation/domain:
    config:
      recursive: true
